baseURL = "https://www.paulobc.com.br"
languageCode = "pt-br"
title = "Paulo Batista"
theme = "m10c"

[params]
author = "Paulo Batista da Costa"
description = "Bacharel em Ciência da Computação, Desenvolvedor, Testador & Analista de Teste Automatizado"


[[params.social]]
name="github"
url="https://github.com/costabatista"

[[params.social]]
name="linkedin"
url="https://www.linkedin.com/in/costabatista/"

[[params.social]]
name="facebook"
url="https://www.facebook.com/paulobatistadacosta7"



# Brown theme
#[params.style]
#  darkestColor = "#463625"
#  darkColor = "#2a3738"
#  primaryColor = "#eeee6a"
#  lightColor = "#96a879"
#  lightestColor = "#ffffff"

# Green theme
#[params.style]
#  darkestColor = "#315659"
#  darkColor = "#253031"
#  primaryColor = "#dad865"
#  lightColor = "#96a879"
#  lightestColor = "#fff"

# Red and black theme
[params.style]
darkestColor = "#d35050"
darkColor = "#212121"
primaryColor = "#ffffff"
lightColor = "#a2a2a2"
lightestColor = "#d3d3d3"
